// This file is auto-generated by scripts/generate-types.sh
// Run: SUPABASE_PROJECT_ID=your-ref bash scripts/generate-types.sh

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Placeholder — run generate-types.sh against your Supabase project
// to populate this file with your actual schema types.
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role?: string
          avatar_url?: string | null
        }
        Update: {
          email?: string
          full_name?: string | null
          role?: string
          avatar_url?: string | null
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      subscription_status:
        | 'trialing'
        | 'active'
        | 'past_due'
        | 'canceled'
        | 'unpaid'
        | 'incomplete'
        | 'incomplete_expired'
        | 'paused'
      update_event_status: 'pending' | 'approved' | 'rejected'
      module_difficulty: 'easy' | 'moderate' | 'intermediate' | 'advanced' | 'expert'
    }
  }
}
